---
- name: Uninstall MongoDB on localhost.
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Stop mongod service.
      service:
        name: mongod
        state: stopped
      register: service_status
      failed_when: service_status|failed and not 'could not find the requested service' in service_status

    - name: Uninstall MongoDB.
      dnf:
        name: mongodb-enterprise
        state: absent
        autoremove: yes
    
    - name: Remove data and log directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/log/mongodb 
        - /var/lib/mongo 

    - name: Done.
      debug:
        msg: "MongoDB has been uninstalled successfully."