---
- name: Uninstall MongoDB on localhost.
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Gather info about installed services.
      tags: debug
      service_facts:

    - name: Print services Check
      tags: debug
      debug:
        msg: "{{ ansible_facts.services['mongod'] }}"

    - name: Stop mongod service.
      tags: debug
      service:
        name: mongod
        state: stopped
      when: "'mongod' in services_check"
    
    - name: Uninstall MongoDB.
      dnf:
        name: mongodb-enterprise
        state: absent
        autoremove: yes
    
    - name: Remove data and log directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/log/mongodb 
        - /var/lib/mongo 

    - name: Done.
      debug:
        msg: "MongoDB has been uninstalled successfully."